version: '3.1'

services:
  jmap:
    image: overture-unipd/jmap:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2000M
        reservations:
          cpus: 1
          memory: 500M

  rethinkdb:
    image: rethinkdb:2.4.2-bullseye-slim
    restart: unless-stopped
    ports:
      - 9000:8080
      - 29015:29015
      - 28015:28015
    volumes:
      - rethinkdb:/data

  minio:
    image: minio/minio:RELEASE.2024-02-24T17-11-14Z
    restart: unless-stopped
    ports:
      - 10000:9000
      - 10001:9001
    command: server --console-address ":9001" http://minio/data
    volumes:
      - minio:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  caddy:
    image: overture-unipd/caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
      # - /tmp/caddy.log:/tmp/caddy.log

volumes:
  rethinkdb:
  minio:
  caddy_data:
