version: '3.1'

services:
  jmap:
    image: overture-unipd/jmap:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2000M
        reservations:
          cpus: 1
          memory: 500M

  rethinkdb:
    image: rethinkdb:2.4.2-bullseye-slim
    restart: unless-stopped
    ports:
      - 9000:8080
      - 29015:29015
      - 28015:28015
    volumes:
      - rethinkdb:/data

  caddy:
    image: overture-unipd/caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
      # - /tmp/caddy.log:/tmp/caddy.log

volumes:
  rethinkdb:
  caddy_data:
