name: Try to build with Gradle on PRs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{secrets.PUSH_TOKEN}} # yeah i know this is a _bad_ workaround
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
    - uses: gradle/gradle-build-action@v2
      id: setup-gradle
      with:
        gradle-version: 8.5
    - run: gradle build
    - uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
    - run: |
        if [[ `git status --porcelain` ]]; then
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push
        fi
      env:
        TZ: Europe/Rome
