/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unipd.overture.jmap;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class IgniteTest {
  @Test
  void appHasAGreeting() {
    Ignite classUnderTest = new Ignite();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
